location: "East US"
resource_group_name: "ml-resource-group-prod"
storage_account_name: "mlstorageprod"
ml_workspace_name: "ml-workspace-prod"
terraform_version: "1.5.5"
terraform_workingdir: "./terraform"
backend_resource_group: "tf-backend-rg"
backend_storage_account: "tfbackendstorage"
backend_container: "tfstate"
